/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmployeeManagement } from "./EmployeeManagement";
export * as factories from "./factories";
export { EmployeeManagement__factory } from "./factories/EmployeeManagement__factory";
